(()=>{
'use strict';
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const TAU=Math.PI*2, clamp=(v,a,b)=>Math.max(a,Math.min(b,v)), rnd=(a,b)=>a+Math.random()*(b-a);
const canvas=$('#game'), ctx=canvas.getContext('2d',{alpha:false});
const ui={start:$('#start'),over:$('#over'),hud:$('#hud'),touch:$('#touch'),preview:$('#preview'),plus:$('#plus'),portrait:$('#portrait'),hp:$('#hp'),hpFill:$('#hpFill'),wave:$('#wave'),kills:$('#kills'),score:$('#score'),ammo:$('#ammo'),reserve:$('#reserve'),weaponName:$('#weaponName'),weaponIcon:$('#weaponIcon'),toast:$('#toast')};
const touchDevice=matchMedia('(hover:none),(pointer:coarse)').matches||navigator.maxTouchPoints>0;
const WORLD={w:2600,h:1900};
const WEAPONS={
 pistol:{name:'ПИСТОЛЕТ',icon:'⌁',mag:12,reserve:84,damage:42,rate:.21,speed:1150,spread:.018,pellets:1,reload:1.0,color:'#ffe9a8'},
 shotgun:{name:'ДРОБОВИК',icon:'≋',mag:6,reserve:30,damage:25,rate:.68,speed:930,spread:.19,pellets:7,reload:1.4,color:'#ffd19b'},
 bow:{name:'ЛУК',icon:'➳',mag:1,reserve:32,damage:105,rate:.72,speed:760,spread:.004,pellets:1,reload:.48,color:'#d7e6bd',arrow:true}
};
let W=innerWidth,H=innerHeight,DPR=1,last=performance.now(),running=false,faceImg=null,toastTimer=0;
let player,enemies=[],shots=[],particles=[],decals=[],props=[],wave=1,kills=0,score=0,spawnLeft=0,spawnTimer=0,between=1.0;
let camera={x:0,y:0,shake:0}, moveTouch={x:0,y:0}, firing=false;
const keys=new Set(), mouse={x:W/2,y:H/2,down:false,moved:false};

function resize(){DPR=Math.min(2,devicePixelRatio||1);W=innerWidth;H=innerHeight;canvas.width=Math.round(W*DPR);canvas.height=Math.round(H*DPR);canvas.style.width=W+'px';canvas.style.height=H+'px';ctx.setTransform(DPR,0,0,DPR,0,0)}
addEventListener('resize',resize,{passive:true});resize();
function norm(x,y){const d=Math.hypot(x,y)||1;return{x:x/d,y:y/d}}
function toast(t){clearTimeout(toastTimer);ui.toast.textContent=t;ui.toast.classList.remove('hidden');toastTimer=setTimeout(()=>ui.toast.classList.add('hidden'),1100)}

function neutralFace(){const c=document.createElement('canvas');c.width=c.height=220;const g=c.getContext('2d');const q=g.createRadialGradient(110,78,10,110,110,125);q.addColorStop(0,'#b6b9ad');q.addColorStop(1,'#465148');g.fillStyle=q;g.fillRect(0,0,220,220);g.fillStyle='#1d251f';g.beginPath();g.arc(110,103,72,0,TAU);g.fill();g.fillStyle='#9da79d';g.beginPath();g.ellipse(110,106,48,58,0,0,TAU);g.fill();g.fillStyle='#273029';g.fillRect(78,95,19,5);g.fillRect(123,95,19,5);g.fillRect(95,139,30,5);return c.toDataURL('image/jpeg',.84)}
function setFace(src){const im=new Image();im.onload=()=>{faceImg=im;ui.preview.src=src;ui.preview.style.display='block';ui.plus.style.display='none';ui.portrait.src=src};im.src=src}
setFace(localStorage.getItem('facefall-face')||neutralFace());
$('#face').addEventListener('change',e=>{const f=e.target.files?.[0];if(!f)return;const r=new FileReader();r.onload=()=>{const im=new Image();im.onload=()=>{const c=document.createElement('canvas');c.width=c.height=320;const g=c.getContext('2d');const s=Math.max(320/im.width,320/im.height),dw=im.width*s,dh=im.height*s;g.drawImage(im,(320-dw)/2,(320-dh)/2,dw,dh);const data=c.toDataURL('image/jpeg',.84);try{localStorage.setItem('facefall-face',data)}catch{}setFace(data);toast('ЛИЦО ГОТОВО')};im.src=r.result};r.readAsDataURL(f)});

function reset(){
 player={x:WORLD.w/2,y:WORLD.h/2,r:22,hp:100,maxHp:100,speed:250,angle:0,weapon:'pistol',cool:0,reloading:0,inv:0,ammo:{pistol:{mag:12,reserve:84},shotgun:{mag:6,reserve:30},bow:{mag:1,reserve:32}}};
 enemies=[];shots=[];particles=[];decals=[];props=[];wave=1;kills=0;score=0;spawnLeft=0;spawnTimer=0;between=.8;camera={x:player.x-W/2,y:player.y-H/2,shake:0};
 for(let i=0;i<65;i++)props.push({x:rnd(70,WORLD.w-70),y:rnd(70,WORLD.h-70),r:rnd(8,24),kind:Math.random()<.58?'rock':'bush',rot:rnd(0,TAU)});
 for(let i=0;i<24;i++)decals.push({x:rnd(0,WORLD.w),y:rnd(0,WORLD.h),r:rnd(22,70),a:rnd(.025,.07),kind:'mud'});
 updateHud();
}
function start(){reset();running=true;last=performance.now();ui.start.classList.add('hidden');ui.over.classList.add('hidden');ui.hud.classList.remove('hidden');if(touchDevice)ui.touch.classList.remove('hidden');audio.unlock();toast('ПЕРВАЯ НОЧЬ')}
function gameOver(){running=false;firing=false;mouse.down=false;ui.hud.classList.add('hidden');ui.touch.classList.add('hidden');$('#finalScore').textContent=score;$('#finalKills').textContent=kills;$('#finalWave').textContent=wave;ui.over.classList.remove('hidden');audio.over()}
$('#play').onclick=start;$('#again').onclick=start;

function selectWeapon(id){if(!player||!WEAPONS[id])return;player.weapon=id;player.reloading=0;$$('.slots button').forEach(b=>b.classList.toggle('active',b.dataset.w===id));updateHud();toast(WEAPONS[id].name)}
$$('.slots button').forEach(b=>b.onclick=()=>selectWeapon(b.dataset.w));
function reload(){if(!running||!player)return;const w=WEAPONS[player.weapon],a=player.ammo[player.weapon];if(player.reloading>0||a.mag>=w.mag||a.reserve<=0)return;player.reloading=w.reload;audio.reload();toast('ПЕРЕЗАРЯДКА')}
function finishReload(){const w=WEAPONS[player.weapon],a=player.ammo[player.weapon],n=Math.min(w.mag-a.mag,a.reserve);a.mag+=n;a.reserve-=n;updateHud()}
function fire(){if(!running||!player)return;const w=WEAPONS[player.weapon],a=player.ammo[player.weapon];if(player.cool>0||player.reloading>0)return;if(a.mag<=0){audio.empty();reload();return}a.mag--;player.cool=w.rate;camera.shake=Math.min(12,camera.shake+(player.weapon==='shotgun'?6:2.5));const ox=player.x+Math.cos(player.angle)*31,oy=player.y+Math.sin(player.angle)*31;for(let i=0;i<w.pellets;i++){const ang=player.angle+rnd(-w.spread,w.spread);shots.push({x:ox,y:oy,px:ox,py:oy,vx:Math.cos(ang)*w.speed,vy:Math.sin(ang)*w.speed,life:w.arrow?1.35:.75,damage:w.damage,arrow:!!w.arrow,angle:ang,color:w.color})}burst(ox,oy,w.arrow?'#dce7c7':'#ffd88f',w.arrow?3:7,90);audio.shot(player.weapon);updateHud()}

function beginWave(){spawnLeft=5+wave*3;spawnTimer=.05;toast('ВОЛНА '+wave);audio.wave()}
function spawnEnemy(){let x,y;const edge=Math.floor(rnd(0,4));if(edge===0){x=rnd(30,WORLD.w-30);y=30}else if(edge===1){x=WORLD.w-30;y=rnd(30,WORLD.h-30)}else if(edge===2){x=rnd(30,WORLD.w-30);y=WORLD.h-30}else{x=30;y=rnd(30,WORLD.h-30)}if(Math.hypot(x-player.x,y-player.y)<520)return spawnEnemy();const elite=wave>2&&Math.random()<Math.min(.22,wave*.025),hp=(elite?165:72)+wave*(elite?12:7);enemies.push({x,y,r:elite?29:rnd(20,23),hp,maxHp:hp,speed:(elite?72:84)+rnd(-8,16)+wave*1.6,damage:elite?22:12,attack:0,stagger:0,elite,phase:rnd(0,TAU)})}
function burst(x,y,color,n=8,speed=130){for(let i=0;i<n;i++){const a=rnd(0,TAU),v=rnd(speed*.25,speed);particles.push({x,y,vx:Math.cos(a)*v,vy:Math.sin(a)*v,life:rnd(.18,.5),max:.5,size:rnd(1.2,3.6),color})}}
function blood(x,y,n=9){burst(x,y,'#751b1b',n,145);if(decals.length<150)decals.push({x:x+rnd(-7,7),y:y+rnd(-7,7),r:rnd(5,13),a:rnd(.16,.32),kind:'blood'})}
function nearestEnemy(){let best=null,bd=Infinity;for(const e of enemies){const d=(e.x-player.x)**2+(e.y-player.y)**2;if(d<bd){bd=d;best=e}}return best}

function update(dt){if(!running)return;player.cool=Math.max(0,player.cool-dt);player.inv=Math.max(0,player.inv-dt);if(player.reloading>0){player.reloading-=dt;if(player.reloading<=0)finishReload()}
 let mx=(keys.has('d')?1:0)-(keys.has('a')?1:0)+moveTouch.x,my=(keys.has('s')?1:0)-(keys.has('w')?1:0)+moveTouch.y;if(mx||my){const n=norm(mx,my);player.x=clamp(player.x+n.x*player.speed*dt,28,WORLD.w-28);player.y=clamp(player.y+n.y*player.speed*dt,28,WORLD.h-28)}
 if(touchDevice){const t=nearestEnemy();if(t)player.angle=Math.atan2(t.y-player.y,t.x-player.x);else if(mx||my)player.angle=Math.atan2(my,mx)}else{const sx=player.x-camera.x,sy=player.y-camera.y;player.angle=Math.atan2(mouse.y-sy,mouse.x-sx)}
 if(mouse.down||firing)fire();
 if(between>0){between-=dt;if(between<=0)beginWave()}else if(spawnLeft>0){spawnTimer-=dt;if(spawnTimer<=0){spawnEnemy();spawnLeft--;spawnTimer=Math.max(.22,.68-wave*.022)}}
 for(let i=shots.length-1;i>=0;i--){const s=shots[i];s.px=s.x;s.py=s.y;s.x+=s.vx*dt;s.y+=s.vy*dt;s.life-=dt;let hit=false;for(let j=enemies.length-1;j>=0&&!hit;j--){const e=enemies[j];if(Math.hypot(s.x-e.x,s.y-e.y)<e.r+4){e.hp-=s.damage;e.stagger=.085;blood(s.x,s.y,s.arrow?5:8);hit=true;if(e.hp<=0){kills++;score+=e.elite?250:100;blood(e.x,e.y,e.elite?25:15);enemies.splice(j,1);audio.down()}}}if(hit||s.life<=0||s.x<0||s.y<0||s.x>WORLD.w||s.y>WORLD.h)shots.splice(i,1)}
 for(const e of enemies){e.phase+=dt*6;e.attack=Math.max(0,e.attack-dt);e.stagger=Math.max(0,e.stagger-dt);const dx=player.x-e.x,dy=player.y-e.y,d=Math.hypot(dx,dy)||1;if(d>player.r+e.r-2){if(e.stagger<=0){e.x+=dx/d*e.speed*dt;e.y+=dy/d*e.speed*dt}}else if(e.attack<=0&&player.inv<=0){player.hp=Math.max(0,player.hp-e.damage);player.inv=.16;e.attack=.75;camera.shake=10;blood(player.x,player.y,4);audio.hurt();if(player.hp<=0){updateHud();gameOver();return}}}
 for(let i=particles.length-1;i>=0;i--){const p=particles[i];p.x+=p.vx*dt;p.y+=p.vy*dt;p.vx*=Math.pow(.05,dt);p.vy*=Math.pow(.05,dt);p.life-=dt;if(p.life<=0)particles.splice(i,1)}
 if(spawnLeft===0&&enemies.length===0&&between<=0){wave++;between=2.25;player.hp=Math.min(100,player.hp+10);player.ammo.pistol.reserve+=10;player.ammo.shotgun.reserve+=4;player.ammo.bow.reserve+=5;toast('ПЕРЕДЫШКА · +10 HP')}
 const tx=player.x-W/2,ty=player.y-H/2;camera.x+=(tx-camera.x)*Math.min(1,dt*5.5);camera.y+=(ty-camera.y)*Math.min(1,dt*5.5);camera.x=clamp(camera.x,0,Math.max(0,WORLD.w-W));camera.y=clamp(camera.y,0,Math.max(0,WORLD.h-H));camera.shake=Math.max(0,camera.shake-dt*30);updateHud()
}
function updateHud(){if(!player)return;ui.hp.textContent=Math.ceil(player.hp);ui.hpFill.style.width=clamp(player.hp,0,100)+'%';ui.wave.textContent=wave;ui.kills.textContent=kills;ui.score.textContent=String(score).padStart(6,'0');const w=WEAPONS[player.weapon],a=player.ammo[player.weapon];ui.weaponName.textContent=w.name;ui.weaponIcon.textContent=w.icon;ui.ammo.textContent=a.mag;ui.reserve.textContent=' / '+a.reserve}

function draw(){ctx.setTransform(DPR,0,0,DPR,0,0);ctx.fillStyle='#0a100c';ctx.fillRect(0,0,W,H);if(!player){fog();return}const sx=rnd(-camera.shake,camera.shake),sy=rnd(-camera.shake,camera.shake);ctx.save();ctx.translate(-camera.x+sx,-camera.y+sy);drawGround();for(const d of decals)drawDecal(d);for(const p of props)drawProp(p);for(const s of shots)drawShot(s);for(const e of enemies)drawEnemy(e);drawPlayer();for(const p of particles)drawParticle(p);ctx.restore();drawLight(sx,sy);if(!touchDevice)crosshair();if(player.inv>0){ctx.fillStyle='rgba(135,15,15,.11)';ctx.fillRect(0,0,W,H)}}
function drawGround(){ctx.fillStyle='#151c16';ctx.fillRect(0,0,WORLD.w,WORLD.h);const step=100;for(let y=0;y<WORLD.h;y+=step)for(let x=0;x<WORLD.w;x+=step){const n=((x*17+y*11)%101)/101;ctx.fillStyle=`rgba(${22+~~(n*10)},${30+~~(n*11)},${23+~~(n*7)},.17)`;ctx.fillRect(x,y,step,step)}ctx.strokeStyle='rgba(205,218,203,.045)';ctx.lineWidth=9;ctx.beginPath();ctx.moveTo(0,WORLD.h*.46);ctx.bezierCurveTo(WORLD.w*.32,WORLD.h*.37,WORLD.w*.62,WORLD.h*.57,WORLD.w,WORLD.h*.48);ctx.stroke();ctx.strokeStyle='rgba(7,10,8,.14)';ctx.lineWidth=3;ctx.stroke()}
function drawDecal(d){ctx.save();ctx.translate(d.x,d.y);ctx.globalAlpha=d.a;ctx.fillStyle=d.kind==='blood'?'#691919':'#080b08';ctx.beginPath();ctx.ellipse(0,0,d.r,d.r*.55,d.r,0,TAU);ctx.fill();ctx.restore()}
function drawProp(p){ctx.save();ctx.translate(p.x,p.y);ctx.rotate(p.rot);if(p.kind==='rock'){ctx.fillStyle='#252b26';ctx.beginPath();ctx.ellipse(0,0,p.r,p.r*.7,0,0,TAU);ctx.fill();ctx.strokeStyle='rgba(255,255,255,.055)';ctx.stroke()}else{ctx.fillStyle='rgba(38,58,40,.66)';for(let i=0;i<5;i++){ctx.rotate(TAU/5);ctx.beginPath();ctx.ellipse(p.r*.5,0,p.r*.82,p.r*.28,0,0,TAU);ctx.fill()}}ctx.restore()}
function drawPlayer(){ctx.save();ctx.translate(player.x,player.y);ctx.rotate(player.angle);ctx.fillStyle='rgba(0,0,0,.3)';ctx.beginPath();ctx.ellipse(-5,13,30,17,0,0,TAU);ctx.fill();ctx.fillStyle='#3f4c42';ctx.fillRect(-14,-17,29,34);ctx.fillStyle='#222a24';ctx.fillRect(-20,-14,8,26);ctx.fillRect(13,-14,8,26);ctx.fillStyle='#2a332d';ctx.fillRect(4,-4,35,9);ctx.fillStyle='#717a72';ctx.fillRect(30,-2,18,5);ctx.restore();ctx.save();ctx.translate(player.x,player.y-16);ctx.beginPath();ctx.arc(0,0,17,0,TAU);ctx.clip();if(faceImg)ctx.drawImage(faceImg,-18,-18,36,36);ctx.restore();ctx.strokeStyle='rgba(196,255,103,.24)';ctx.lineWidth=1;ctx.beginPath();ctx.arc(player.x,player.y,29,0,TAU);ctx.stroke()}
function drawEnemy(e){ctx.save();ctx.translate(e.x,e.y);ctx.rotate(Math.atan2(player.y-e.y,player.x-e.x));ctx.fillStyle='rgba(0,0,0,.3)';ctx.beginPath();ctx.ellipse(-4,11,e.r*1.05,e.r*.6,0,0,TAU);ctx.fill();ctx.fillStyle=e.elite?'#514b38':'#3e473f';ctx.fillRect(-e.r*.52,-e.r*.68,e.r*1.05,e.r*1.33);ctx.fillStyle=e.elite?'#85836a':'#6e786d';ctx.beginPath();ctx.arc(e.r*.13,-e.r*.76,e.r*.52,0,TAU);ctx.fill();ctx.fillStyle='#381313';ctx.fillRect(e.r*.37,-e.r*.85,4,3);ctx.fillStyle='#2a322b';ctx.fillRect(-e.r*.69,-e.r*.3,e.r*.25,e.r);ctx.fillRect(e.r*.45,-e.r*.26,e.r*.25,e.r);if(e.elite){ctx.strokeStyle='rgba(196,255,103,.43)';ctx.lineWidth=2;ctx.beginPath();ctx.arc(0,0,e.r+4,0,TAU);ctx.stroke()}ctx.restore();if(e.elite&&e.hp<e.maxHp){ctx.fillStyle='rgba(0,0,0,.55)';ctx.fillRect(e.x-22,e.y-e.r-14,44,4);ctx.fillStyle='#b9df67';ctx.fillRect(e.x-22,e.y-e.r-14,44*(e.hp/e.maxHp),4)}}
function drawShot(s){ctx.save();if(s.arrow){ctx.translate(s.x,s.y);ctx.rotate(s.angle);ctx.strokeStyle='#c9b990';ctx.lineWidth=2;ctx.beginPath();ctx.moveTo(-18,0);ctx.lineTo(8,0);ctx.stroke();ctx.fillStyle='#dfe3d4';ctx.beginPath();ctx.moveTo(11,0);ctx.lineTo(5,-3);ctx.lineTo(5,3);ctx.closePath();ctx.fill()}else{ctx.strokeStyle=s.color;ctx.globalAlpha=.88;ctx.lineWidth=1.2;ctx.beginPath();ctx.moveTo(s.px,s.py);ctx.lineTo(s.x,s.y);ctx.stroke();ctx.fillStyle='#fff7d6';ctx.beginPath();ctx.arc(s.x,s.y,1.5,0,TAU);ctx.fill()}ctx.restore()}
function drawParticle(p){ctx.globalAlpha=clamp(p.life/p.max,0,1);ctx.fillStyle=p.color;ctx.beginPath();ctx.arc(p.x,p.y,p.size,0,TAU);ctx.fill();ctx.globalAlpha=1}
function drawLight(shx,shy){const x=player.x-camera.x+shx,y=player.y-camera.y+shy;const r=Math.max(W,H)*.76,g=ctx.createRadialGradient(x,y,70,x,y,r);g.addColorStop(0,'rgba(2,5,3,0)');g.addColorStop(.44,'rgba(2,5,3,.08)');g.addColorStop(1,'rgba(0,2,1,.8)');ctx.fillStyle=g;ctx.fillRect(0,0,W,H);const v=ctx.createRadialGradient(W/2,H/2,Math.min(W,H)*.22,W/2,H/2,Math.max(W,H)*.72);v.addColorStop(0,'rgba(0,0,0,0)');v.addColorStop(1,'rgba(0,0,0,.44)');ctx.fillStyle=v;ctx.fillRect(0,0,W,H)}
function fog(){const g=ctx.createRadialGradient(W*.5,H*.36,20,W*.5,H*.5,Math.max(W,H)*.78);g.addColorStop(0,'rgba(60,85,60,.12)');g.addColorStop(1,'rgba(2,4,3,.5)');ctx.fillStyle=g;ctx.fillRect(0,0,W,H)}
function crosshair(){ctx.strokeStyle='rgba(235,242,236,.75)';ctx.lineWidth=1;ctx.beginPath();ctx.arc(mouse.x,mouse.y,8,0,TAU);ctx.moveTo(mouse.x-14,mouse.y);ctx.lineTo(mouse.x-7,mouse.y);ctx.moveTo(mouse.x+7,mouse.y);ctx.lineTo(mouse.x+14,mouse.y);ctx.moveTo(mouse.x,mouse.y-14);ctx.lineTo(mouse.x,mouse.y-7);ctx.moveTo(mouse.x,mouse.y+7);ctx.lineTo(mouse.x,mouse.y+14);ctx.stroke()}

addEventListener('keydown',e=>{const k=e.key.toLowerCase();keys.add(k);if(k==='1')selectWeapon('pistol');if(k==='2')selectWeapon('shotgun');if(k==='3')selectWeapon('bow');if(k==='r')reload()});addEventListener('keyup',e=>keys.delete(e.key.toLowerCase()));
canvas.addEventListener('pointermove',e=>{if(e.pointerType==='mouse'){mouse.x=e.clientX;mouse.y=e.clientY;mouse.moved=true}});canvas.addEventListener('pointerdown',e=>{if(e.pointerType==='mouse'&&e.button===0){mouse.down=true;audio.unlock()}});addEventListener('pointerup',e=>{if(e.pointerType==='mouse')mouse.down=false});canvas.oncontextmenu=e=>e.preventDefault();
const joy=$('#joy'),stick=$('#stick');let joyPointer=null;
function joyMove(e){const r=joy.getBoundingClientRect(),cx=r.left+r.width/2,cy=r.top+r.height/2,max=r.width*.32;let dx=e.clientX-cx,dy=e.clientY-cy,m=Math.hypot(dx,dy);if(m>max){dx=dx/m*max;dy=dy/m*max}stick.style.transform=`translate(${dx}px,${dy}px)`;moveTouch.x=dx/max;moveTouch.y=dy/max}
joy.addEventListener('pointerdown',e=>{joyPointer=e.pointerId;joy.setPointerCapture(e.pointerId);joyMove(e);e.preventDefault()});joy.addEventListener('pointermove',e=>{if(e.pointerId===joyPointer)joyMove(e)});function joyEnd(e){if(e.pointerId!==joyPointer)return;joyPointer=null;moveTouch.x=moveTouch.y=0;stick.style.transform='translate(0,0)'}joy.addEventListener('pointerup',joyEnd);joy.addEventListener('pointercancel',joyEnd);
const fireBtn=$('#fire');fireBtn.addEventListener('pointerdown',e=>{firing=true;audio.unlock();fireBtn.setPointerCapture?.(e.pointerId);e.preventDefault()});const stopFire=e=>{firing=false;e?.preventDefault?.()};fireBtn.addEventListener('pointerup',stopFire);fireBtn.addEventListener('pointercancel',stopFire);fireBtn.addEventListener('pointerleave',e=>{if(e.buttons===0)firing=false});
$('#reload').onclick=reload;$('#swap').onclick=()=>{if(!player)return;const ids=['pistol','shotgun','bow'];selectWeapon(ids[(ids.indexOf(player.weapon)+1)%ids.length])};

function audioSystem(){let ac,master;function unlock(){if(!ac){ac=new (window.AudioContext||window.webkitAudioContext)();master=ac.createGain();master.gain.value=.12;master.connect(ac.destination)}if(ac.state==='suspended')ac.resume()}function tone(f,d,type='square',vol=.1,end=f){if(!ac)return;const o=ac.createOscillator(),g=ac.createGain();o.type=type;o.frequency.setValueAtTime(f,ac.currentTime);o.frequency.exponentialRampToValueAtTime(Math.max(30,end),ac.currentTime+d);g.gain.setValueAtTime(vol,ac.currentTime);g.gain.exponentialRampToValueAtTime(.001,ac.currentTime+d);o.connect(g);g.connect(master);o.start();o.stop(ac.currentTime+d)}function noise(d=.07,v=.16){if(!ac)return;const n=Math.floor(ac.sampleRate*d),b=ac.createBuffer(1,n,ac.sampleRate),a=b.getChannelData(0);for(let i=0;i<n;i++)a[i]=(Math.random()*2-1)*(1-i/n);const s=ac.createBufferSource(),g=ac.createGain();s.buffer=b;g.gain.value=v;s.connect(g);g.connect(master);s.start()}return{unlock,shot(id){if(id==='pistol'){noise(.055,.17);tone(130,.06,'square',.07,65)}else if(id==='shotgun'){noise(.13,.22);tone(88,.12,'sawtooth',.09,42)}else tone(410,.07,'triangle',.05,180)},reload(){tone(620,.04,'square',.02,430);setTimeout(()=>tone(820,.04,'square',.02,620),70)},empty(){tone(170,.035,'square',.025,120)},hurt(){tone(76,.13,'sawtooth',.05,45)},down(){tone(112,.1,'sawtooth',.03,55)},wave(){tone(430,.08,'sine',.04,610);setTimeout(()=>tone(640,.1,'sine',.035,830),80)},over(){tone(135,.48,'sawtooth',.055,60)}}}
const audio=audioSystem();
function loop(now){const dt=Math.min(.035,(now-last)/1000||0);last=now;update(dt);draw();requestAnimationFrame(loop)}requestAnimationFrame(loop);
})();
