(()=>{
'use strict';
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)],TAU=Math.PI*2,clamp=(v,a,b)=>Math.max(a,Math.min(b,v));
const canvas=$('#game'),ctx=canvas.getContext('2d',{alpha:false});
const ui={start:$('#start'),over:$('#over'),hud:$('#hud'),touch:$('#touch'),preview:$('#preview'),plus:$('#plus'),portrait:$('#portrait'),hp:$('#hp'),hpFill:$('#hpFill'),wave:$('#wave'),kills:$('#kills'),score:$('#score'),ammo:$('#ammo'),reserve:$('#reserve'),weaponName:$('#weaponName'),weaponIcon:$('#weaponIcon'),toast:$('#toast')};
const isTouch=matchMedia('(hover:none),(pointer:coarse)').matches;
let DPR=1,W=innerWidth,H=innerHeight,last=performance.now(),running=false,faceImg=null,toastTimer=0;
let player,enemies=[],shots=[],particles=[],decals=[],props=[],wave=1,kills=0,score=0,nextWave=0,spawnLeft=0,spawnTimer=0,camera={x:0,y:0,shake:0};
const keys=new Set(),mouse={x:W/2,y:H/2,down:false,moved:false},moveTouch={x:0,y:0},aimTouch={x:1,y:0};
const WORLD={w:2600,h:1900};
const WEAPONS={
 pistol:{name:'ПИСТОЛЕТ',icon:'⌁',mag:12,reserve:72,damage:34,rate:.22,speed:1100,spread:.025,pellets:1,reload:1.0,color:'#fff0aa'},
 shotgun:{name:'ДРОБОВИК',icon:'≋',mag:6,reserve:30,damage:22,rate:.72,speed:900,spread:.22,pellets:7,reload:1.45,color:'#ffd3a0'},
 bow:{name:'ЛУК',icon:'➳',mag:1,reserve:30,damage:90,rate:.82,speed:760,spread:.008,pellets:1,reload:.55,color:'#d7edb8',arrow:true}
};
function resize(){DPR=Math.min(2,devicePixelRatio||1);W=innerWidth;H=innerHeight;canvas.width=Math.floor(W*DPR);canvas.height=Math.floor(H*DPR);canvas.style.width=W+'px';canvas.style.height=H+'px';ctx.setTransform(DPR,0,0,DPR,0,0)}
addEventListener('resize',resize);resize();
function neutralFace(){const c=document.createElement('canvas');c.width=c.height=180;const x=c.getContext('2d');const g=x.createRadialGradient(90,62,12,90,90,95);g.addColorStop(0,'#a9b5a6');g.addColorStop(1,'#455047');x.fillStyle=g;x.fillRect(0,0,180,180);x.fillStyle='#202722';x.beginPath();x.arc(90,88,58,0,TAU);x.fill();x.fillStyle='#9ba69c';x.beginPath();x.arc(90,75,34,0,TAU);x.fill();x.fillStyle='#2b342d';x.fillRect(65,69,13,5);x.fillRect(102,69,13,5);x.fillStyle='#6e796f';x.fillRect(86,76,8,17);x.fillStyle='#3a453d';x.fillRect(76,102,28,5);return c.toDataURL('image/jpeg',.82)}
function setFace(src){const img=new Image();img.onload=()=>{faceImg=img;ui.preview.src=src;ui.preview.style.display='block';ui.plus.style.display='none';ui.portrait.src=src};img.src=src}
setFace(localStorage.getItem('facefall-face')||neutralFace());
$('#face').addEventListener('change',e=>{const f=e.target.files&&e.target.files[0];if(!f)return;const r=new FileReader();r.onload=()=>{const im=new Image();im.onload=()=>{const c=document.createElement('canvas'),s=320;c.width=c.height=s;const x=c.getContext('2d');const scale=Math.max(s/im.width,s/im.height),dw=im.width*scale,dh=im.height*scale;x.drawImage(im,(s-dw)/2,(s-dh)/2,dw,dh);const data=c.toDataURL('image/jpeg',.84);localStorage.setItem('facefall-face',data);setFace(data);toast('ЛИЦО СОХРАНЕНО ЛОКАЛЬНО')};im.src=r.result};r.readAsDataURL(f)});
function toast(t){clearTimeout(toastTimer);ui.toast.textContent=t;ui.toast.classList.remove('hidden');toastTimer=setTimeout(()=>ui.toast.classList.add('hidden'),1200)}
function rnd(a,b){return a+Math.random()*(b-a)}
function dist(a,b){return Math.hypot(a.x-b.x,a.y-b.y)}
function norm(x,y){const m=Math.hypot(x,y)||1;return{x:x/m,y:y/m}}
function reset(){player={x:WORLD.w/2,y:WORLD.h/2,r:24,hp:100,maxHp:100,speed:245,angle:0,weapon:'pistol',cool:0,reloading:0,hitFlash:0,ammo:{pistol:{mag:12,reserve:72},shotgun:{mag:6,reserve:30},bow:{mag:1,reserve:30}}};enemies=[];shots=[];particles=[];decals=[];props=[];wave=1;kills=0;score=0;nextWave=1.5;spawnLeft=0;spawnTimer=0;camera={x:player.x-W/2,y:player.y-H/2,shake:0};makeWorld();updateHud()}
function makeWorld(){for(let i=0;i<95;i++){props.push({x:rnd(80,WORLD.w-80),y:rnd(80,WORLD.h-80),r:rnd(7,22),kind:Math.random()<.72?'rock':'bush',rot:rnd(0,TAU)})}for(let i=0;i<28;i++)decals.push({x:rnd(0,WORLD.w),y:rnd(0,WORLD.h),r:rnd(20,70),a:rnd(.02,.07),kind:'mud'})}
function start(){reset();running=true;last=performance.now();ui.start.classList.add('hidden');ui.over.classList.add('hidden');ui.hud.classList.remove('hidden');if(isTouch)ui.touch.classList.remove('hidden');audio.unlock()}
function end(){running=false;mouse.down=false;ui.hud.classList.add('hidden');ui.touch.classList.add('hidden');$('#finalScore').textContent=score;$('#finalKills').textContent=kills;$('#finalWave').textContent=wave;ui.over.classList.remove('hidden');audio.over()}
$('#play').onclick=start;$('#again').onclick=start;
function selectWeapon(id){if(!player||!WEAPONS[id])return;player.weapon=id;player.reloading=0;$$('.slots button').forEach(b=>b.classList.toggle('active',b.dataset.w===id));updateHud()}
$$('.slots button').forEach(b=>b.onclick=()=>selectWeapon(b.dataset.w));
function reload(){if(!running||!player)return;const w=WEAPONS[player.weapon],a=player.ammo[player.weapon];if(player.reloading>0||a.mag>=w.mag||a.reserve<=0)return;player.reloading=w.reload;audio.reload();toast('ПЕРЕЗАРЯДКА')}
function finishReload(){const w=WEAPONS[player.weapon],a=player.ammo[player.weapon],need=w.mag-a.mag,take=Math.min(need,a.reserve);a.mag+=take;a.reserve-=take;updateHud()}
function shoot(){const w=WEAPONS[player.weapon],a=player.ammo[player.weapon];if(player.cool>0||player.reloading>0)return;if(a.mag<=0){reload();audio.empty();return}a.mag--;player.cool=w.rate;camera.shake+=w===WEAPONS.shotgun?7:3;for(let i=0;i<w.pellets;i++){const ang=player.angle+rnd(-w.spread,w.spread);shots.push({x:player.x+Math.cos(ang)*30,y:player.y+Math.sin(ang)*30,px:player.x,py:player.y,vx:Math.cos(ang)*w.speed,vy:Math.sin(ang)*w.speed,life:w.arrow?1.35:.72,damage:w.damage,arrow:!!w.arrow,color:w.color,angle:ang})}burst(player.x+Math.cos(player.angle)*32,player.y+Math.sin(player.angle)*32,w.arrow?'#d6e8bf':'#ffd889',w.arrow?3:7,90);audio.shot(player.weapon);updateHud()}
function beginWave(){spawnLeft=5+wave*3;spawnTimer=.1;toast('ВОЛНА '+wave);audio.wave()}
function spawnEnemy(){let x,y;const edge=Math.floor(Math.random()*4);if(edge===0){x=rnd(20,WORLD.w-20);y=20}else if(edge===1){x=WORLD.w-20;y=rnd(20,WORLD.h-20)}else if(edge===2){x=rnd(20,WORLD.w-20);y=WORLD.h-20}else{x=20;y=rnd(20,WORLD.h-20)};if(Math.hypot(x-player.x,y-player.y)<560)return spawnEnemy();const elite=wave>2&&Math.random()<Math.min(.18,.025*wave);const hp=elite?150+wave*10:68+wave*6;enemies.push({x,y,r:elite?31:23,hp,maxHp:hp,speed:(elite?74:88)+rnd(-10,18)+wave*1.7,damage:elite?24:14,attack:0,elite,phase:rnd(0,TAU),stagger:0})}
function burst(x,y,color,n=8,spd=120){for(let i=0;i<n;i++){const a=rnd(0,TAU),v=rnd(spd*.25,spd);particles.push({x,y,vx:Math.cos(a)*v,vy:Math.sin(a)*v,life:rnd(.18,.55),max:.55,size:rnd(1,3.5),color})}}
function blood(x,y,n=10){burst(x,y,'#6f1717',n,150);if(decals.length<140)decals.push({x:x+rnd(-8,8),y:y+rnd(-8,8),r:rnd(5,13),a:rnd(.16,.32),kind:'blood'})}
function update(dt){if(!running)return;player.cool=Math.max(0,player.cool-dt);player.hitFlash=Math.max(0,player.hitFlash-dt);if(player.reloading>0){player.reloading-=dt;if(player.reloading<=0)finishReload()}
 let mx=(keys.has('d')?1:0)-(keys.has('a')?1:0)+moveTouch.x,my=(keys.has('s')?1:0)-(keys.has('w')?1:0)+moveTouch.y;if(mx||my){const n=norm(mx,my);player.x=clamp(player.x+n.x*player.speed*dt,30,WORLD.w-30);player.y=clamp(player.y+n.y*player.speed*dt,30,WORLD.h-30)}
 const sx=player.x-camera.x,sy=player.y-camera.y;if(isTouch&&!mouse.moved)player.angle=Math.atan2(aimTouch.y,aimTouch.x);else player.angle=Math.atan2(mouse.y-sy,mouse.x-sx);if(mouse.down)shoot();
 if(nextWave>0){nextWave-=dt;if(nextWave<=0)beginWave()}if(spawnLeft>0){spawnTimer-=dt;if(spawnTimer<=0){spawnEnemy();spawnLeft--;spawnTimer=Math.max(.18,.7-wave*.025)}}
 for(let i=shots.length-1;i>=0;i--){const s=shots[i];s.px=s.x;s.py=s.y;s.x+=s.vx*dt;s.y+=s.vy*dt;s.life-=dt;let hit=false;for(let j=enemies.length-1;j>=0&&!hit;j--){const e=enemies[j];if(Math.hypot(s.x-e.x,s.y-e.y)<e.r+3){e.hp-=s.damage;e.stagger=.09;blood(s.x,s.y,s.arrow?5:8);hit=true;if(e.hp<=0){kills++;score+=e.elite?250:100;blood(e.x,e.y,e.elite?26:16);audio.down();enemies.splice(j,1)}}}if(hit||s.life<=0||s.x<0||s.y<0||s.x>WORLD.w||s.y>WORLD.h)shots.splice(i,1)}
 for(let i=enemies.length-1;i>=0;i--){const e=enemies[i];e.phase+=dt*6;e.attack=Math.max(0,e.attack-dt);e.stagger=Math.max(0,e.stagger-dt);const dx=player.x-e.x,dy=player.y-e.y,d=Math.hypot(dx,dy)||1;if(e.stagger<=0&&d>player.r+e.r-3){e.x+=dx/d*e.speed*dt;e.y+=dy/d*e.speed*dt}else if(d<=player.r+e.r+3&&e.attack<=0){player.hp-=e.damage;e.attack=.78;player.hitFlash=.12;camera.shake+=9;blood(player.x,player.y,5);audio.hurt();if(player.hp<=0){player.hp=0;updateHud();end();return}}}
 for(let i=particles.length-1;i>=0;i--){const p=particles[i];p.x+=p.vx*dt;p.y+=p.vy*dt;p.vx*=Math.pow(.04,dt);p.vy*=Math.pow(.04,dt);p.life-=dt;if(p.life<=0)particles.splice(i,1)}
 if(spawnLeft===0&&enemies.length===0&&nextWave<=0){wave++;nextWave=2.4;player.hp=Math.min(player.maxHp,player.hp+10);for(const id of Object.keys(player.ammo)){player.ammo[id].reserve+=id==='pistol'?10:id==='shotgun'?4:5}toast('ПЕРЕДЫШКА +10 HP')}
 const tx=player.x-W/2,ty=player.y-H/2;camera.x+=(tx-camera.x)*Math.min(1,dt*5.5);camera.y+=(ty-camera.y)*Math.min(1,dt*5.5);camera.x=clamp(camera.x,0,Math.max(0,WORLD.w-W));camera.y=clamp(camera.y,0,Math.max(0,WORLD.h-H));camera.shake=Math.max(0,camera.shake-dt*28);updateHud()}
function updateHud(){if(!player)return;ui.hp.textContent=Math.ceil(player.hp);ui.hpFill.style.width=clamp(player.hp,0,100)+'%';ui.wave.textContent=wave;ui.kills.textContent=kills;ui.score.textContent=String(score).padStart(6,'0');const w=WEAPONS[player.weapon],a=player.ammo[player.weapon];ui.weaponName.textContent=w.name;ui.weaponIcon.textContent=w.icon;ui.ammo.textContent=a.mag;ui.reserve.textContent=' / '+a.reserve}
function draw(){ctx.setTransform(DPR,0,0,DPR,0,0);ctx.fillStyle='#0c120e';ctx.fillRect(0,0,W,H);if(!player){fog();return}const shx=rnd(-camera.shake,camera.shake),shy=rnd(-camera.shake,camera.shake);ctx.save();ctx.translate(-camera.x+shx,-camera.y+shy);ground();for(const d of decals)drawDecal(d);for(const p of props)drawProp(p);for(const s of shots)drawShot(s);for(const e of enemies)drawEnemy(e);drawPlayer();for(const p of particles)drawParticle(p);ctx.restore();lighting(shx,shy);if(!isTouch)crosshair();if(player.hitFlash>0){ctx.fillStyle='rgba(150,20,20,.12)';ctx.fillRect(0,0,W,H)}}
function ground(){ctx.fillStyle='#141b15';ctx.fillRect(0,0,WORLD.w,WORLD.h);const size=96;for(let y=0;y<WORLD.h;y+=size)for(let x=0;x<WORLD.w;x+=size){const n=((x*13+y*7)%97)/97;ctx.fillStyle=`rgba(${24+Math.floor(n*8)},${31+Math.floor(n*9)},${24+Math.floor(n*6)},.16)`;ctx.fillRect(x,y,size,size)}ctx.strokeStyle='rgba(222,232,215,.035)';ctx.lineWidth=2;ctx.beginPath();ctx.moveTo(80,WORLD.h*.43);ctx.bezierCurveTo(WORLD.w*.3,WORLD.h*.35,WORLD.w*.62,WORLD.h*.56,WORLD.w-80,WORLD.h*.47);ctx.stroke()}
function drawDecal(d){ctx.save();ctx.translate(d.x,d.y);ctx.globalAlpha=d.a;ctx.fillStyle=d.kind==='blood'?'#601818':'#080b08';ctx.beginPath();ctx.ellipse(0,0,d.r,d.r*.55,d.r,.0,TAU);ctx.fill();ctx.restore()}
function drawProp(p){ctx.save();ctx.translate(p.x,p.y);ctx.rotate(p.rot);if(p.kind==='rock'){ctx.fillStyle='#242a25';ctx.beginPath();ctx.ellipse(0,0,p.r,p.r*.7,0,0,TAU);ctx.fill();ctx.strokeStyle='rgba(255,255,255,.06)';ctx.stroke()}else{ctx.fillStyle='rgba(40,58,40,.7)';for(let i=0;i<5;i++){ctx.rotate(TAU/5);ctx.beginPath();ctx.ellipse(p.r*.5,0,p.r*.8,p.r*.27,0,0,TAU);ctx.fill()}}ctx.restore()}
function drawPlayer(){ctx.save();ctx.translate(player.x,player.y);ctx.rotate(player.angle);ctx.fillStyle='rgba(0,0,0,.28)';ctx.beginPath();ctx.ellipse(-5,11,29,17,0,0,TAU);ctx.fill();ctx.fillStyle='#39483d';ctx.fillRect(-14,-18,30,36);ctx.fillStyle='#202823';ctx.fillRect(-20,-15,9,28);ctx.fillRect(13,-15,9,28);ctx.fillStyle='#2b342e';ctx.fillRect(4,-5,36,10);ctx.fillStyle='#68736b';ctx.fillRect(31,-3,18,6);ctx.rotate(-player.angle);ctx.beginPath();ctx.arc(0,-16,17,0,TAU);ctx.clip();if(faceImg)ctx.drawImage(faceImg,-18,-34,36,36);ctx.restore();ctx.save();ctx.translate(player.x,player.y);ctx.strokeStyle='rgba(196,255,103,.22)';ctx.lineWidth=1;ctx.beginPath();ctx.arc(0,0,29,0,TAU);ctx.stroke();ctx.restore()}
function drawEnemy(e){ctx.save();ctx.translate(e.x,e.y);const a=Math.atan2(player.y-e.y,player.x-e.x);ctx.rotate(a);ctx.fillStyle='rgba(0,0,0,.27)';ctx.beginPath();ctx.ellipse(-4,10,e.r*1.05,e.r*.6,0,0,TAU);ctx.fill();ctx.fillStyle=e.elite?'#514a36':'#3e463e';ctx.fillRect(-e.r*.55,-e.r*.72,e.r*1.1,e.r*1.4);ctx.fillStyle=e.elite?'#7a8061':'#6d786c';ctx.beginPath();ctx.arc(e.r*.16,-e.r*.78,e.r*.54,0,TAU);ctx.fill();ctx.fillStyle='#3a1515';ctx.fillRect(e.r*.42,-e.r*.88,4,3);ctx.fillStyle='#293129';ctx.fillRect(-e.r*.72,-e.r*.35,e.r*.28,e.r*1.15);ctx.fillRect(e.r*.47,-e.r*.28,e.r*.28,e.r*1.1);if(e.elite){ctx.strokeStyle='rgba(205,255,115,.42)';ctx.lineWidth=2;ctx.beginPath();ctx.arc(0,0,e.r+4,0,TAU);ctx.stroke()}ctx.restore();if(e.elite&&e.hp<e.maxHp){ctx.fillStyle='rgba(0,0,0,.55)';ctx.fillRect(e.x-22,e.y-e.r-15,44,4);ctx.fillStyle='#b8df61';ctx.fillRect(e.x-22,e.y-e.r-15,44*(e.hp/e.maxHp),4)}}
function drawShot(s){ctx.save();if(s.arrow){ctx.translate(s.x,s.y);ctx.rotate(s.angle);ctx.strokeStyle='#c7b78f';ctx.lineWidth=2;ctx.beginPath();ctx.moveTo(-18,0);ctx.lineTo(9,0);ctx.stroke();ctx.fillStyle='#d4d4c7';ctx.beginPath();ctx.moveTo(11,0);ctx.lineTo(5,-3);ctx.lineTo(5,3);ctx.closePath();ctx.fill()}else{ctx.strokeStyle=s.color;ctx.lineWidth=1.2;ctx.globalAlpha=.86;ctx.beginPath();ctx.moveTo(s.px,s.py);ctx.lineTo(s.x,s.y);ctx.stroke();ctx.fillStyle='#fff9da';ctx.beginPath();ctx.arc(s.x,s.y,1.5,0,TAU);ctx.fill()}ctx.restore()}
function drawParticle(p){ctx.globalAlpha=clamp(p.life/p.max,0,1);ctx.fillStyle=p.color;ctx.beginPath();ctx.arc(p.x,p.y,p.size,0,TAU);ctx.fill();ctx.globalAlpha=1}
function lighting(shx=0,shy=0){const px=player.x-camera.x+shx,py=player.y-camera.y+shy;const g=ctx.createRadialGradient(px,py,70,px,py,Math.max(W,H)*.7);g.addColorStop(0,'rgba(3,6,4,0)');g.addColorStop(.46,'rgba(3,6,4,.08)');g.addColorStop(1,'rgba(1,3,2,.78)');ctx.fillStyle=g;ctx.fillRect(0,0,W,H);const v=ctx.createRadialGradient(W/2,H/2,Math.min(W,H)*.25,W/2,H/2,Math.max(W,H)*.72);v.addColorStop(0,'rgba(0,0,0,0)');v.addColorStop(1,'rgba(0,0,0,.46)');ctx.fillStyle=v;ctx.fillRect(0,0,W,H)}
function fog(){const g=ctx.createRadialGradient(W*.5,H*.42,20,W*.5,H*.5,Math.max(W,H)*.8);g.addColorStop(0,'rgba(50,72,55,.15)');g.addColorStop(1,'rgba(2,4,3,.4)');ctx.fillStyle=g;ctx.fillRect(0,0,W,H)}
function crosshair(){ctx.save();ctx.strokeStyle='rgba(229,238,230,.78)';ctx.lineWidth=1;ctx.beginPath();ctx.arc(mouse.x,mouse.y,8,0,TAU);ctx.moveTo(mouse.x-14,mouse.y);ctx.lineTo(mouse.x-7,mouse.y);ctx.moveTo(mouse.x+7,mouse.y);ctx.lineTo(mouse.x+14,mouse.y);ctx.moveTo(mouse.x,mouse.y-14);ctx.lineTo(mouse.x,mouse.y-7);ctx.moveTo(mouse.x,mouse.y+7);ctx.lineTo(mouse.x,mouse.y+14);ctx.stroke();ctx.restore()}
addEventListener('keydown',e=>{const k=e.key.toLowerCase();keys.add(k);if(k==='1')selectWeapon('pistol');if(k==='2')selectWeapon('shotgun');if(k==='3')selectWeapon('bow');if(k==='r')reload()});addEventListener('keyup',e=>keys.delete(e.key.toLowerCase()));canvas.addEventListener('mousemove',e=>{mouse.x=e.clientX;mouse.y=e.clientY;mouse.moved=true});canvas.addEventListener('mousedown',e=>{if(e.button===0)mouse.down=true;audio.unlock()});addEventListener('mouseup',e=>{if(e.button===0)mouse.down=false});canvas.oncontextmenu=e=>e.preventDefault();
const joy=$('#joy'),stick=$('#stick');let joyId=null;function joyMove(t){const r=joy.getBoundingClientRect(),cx=r.left+r.width/2,cy=r.top+r.height/2,max=r.width*.32;let dx=t.clientX-cx,dy=t.clientY-cy,m=Math.hypot(dx,dy);if(m>max){dx=dx/m*max;dy=dy/m*max}stick.style.transform=`translate(${dx}px,${dy}px)`;moveTouch.x=dx/max;moveTouch.y=dy/max;if(Math.hypot(moveTouch.x,moveTouch.y)>.12){const n=norm(moveTouch.x,moveTouch.y);aimTouch=n}}joy.addEventListener('touchstart',e=>{joyId=e.changedTouches[0].identifier;joyMove(e.changedTouches[0]);e.preventDefault()},{passive:false});joy.addEventListener('touchmove',e=>{for(const t of e.changedTouches)if(t.identifier===joyId)joyMove(t);e.preventDefault()},{passive:false});joy.addEventListener('touchend',e=>{for(const t of e.changedTouches)if(t.identifier===joyId){joyId=null;moveTouch.x=moveTouch.y=0;stick.style.transform='translate(0,0)'}e.preventDefault()},{passive:false});
$('#fire').addEventListener('touchstart',e=>{mouse.down=true;audio.unlock();e.preventDefault()},{passive:false});$('#fire').addEventListener('touchend',e=>{mouse.down=false;e.preventDefault()},{passive:false});$('#reload').onclick=reload;$('#swap').onclick=()=>{if(!player)return;const ids=['pistol','shotgun','bow'];selectWeapon(ids[(ids.indexOf(player.weapon)+1)%ids.length])};
function audioSystem(){let ac,master;function unlock(){if(!ac){ac=new (window.AudioContext||window.webkitAudioContext)();master=ac.createGain();master.gain.value=.15;master.connect(ac.destination)}if(ac.state==='suspended')ac.resume()}function tone(f,d,type='square',vol=.15,end=f){if(!ac)return;const o=ac.createOscillator(),g=ac.createGain();o.type=type;o.frequency.setValueAtTime(f,ac.currentTime);o.frequency.exponentialRampToValueAtTime(Math.max(30,end),ac.currentTime+d);g.gain.setValueAtTime(vol,ac.currentTime);g.gain.exponentialRampToValueAtTime(.001,ac.currentTime+d);o.connect(g);g.connect(master);o.start();o.stop(ac.currentTime+d)}function noise(d=.08,v=.16){if(!ac)return;const n=Math.floor(ac.sampleRate*d),b=ac.createBuffer(1,n,ac.sampleRate),a=b.getChannelData(0);for(let i=0;i<n;i++)a[i]=(Math.random()*2-1)*(1-i/n);const s=ac.createBufferSource(),g=ac.createGain();s.buffer=b;g.gain.value=v;s.connect(g);g.connect(master);s.start()}return{unlock,shot(id){if(id==='pistol'){noise(.06,.18);tone(130,.06,'square',.08,65)}else if(id==='shotgun'){noise(.14,.24);tone(90,.12,'sawtooth',.1,45)}else{tone(420,.07,'triangle',.06,180)}},reload(){tone(600,.04,'square',.025,420);setTimeout(()=>tone(850,.04,'square',.02,620),80)},empty(){tone(170,.035,'square',.025,120)},hurt(){tone(78,.14,'sawtooth',.055,48)},down(){tone(110,.12,'sawtooth',.035,55)},wave(){tone(420,.08,'sine',.05,610);setTimeout(()=>tone(640,.1,'sine',.04,840),85)},over(){tone(140,.5,'sawtooth',.06,65)}}}const audio=audioSystem();
function loop(now){const dt=Math.min(.035,(now-last)/1000||0);last=now;update(dt);draw();requestAnimationFrame(loop)}requestAnimationFrame(loop);
})();
