const boot=window.FacefallBoot||(window.FacefallBoot={selectedCamera:'top',pendingStart:false});
const sleep=ms=>new Promise((_,rej)=>setTimeout(()=>rej(new Error('3D engine timeout')),ms));
async function loadThree(){
  const tries=['/vendor/three.js','https://cdn.jsdelivr.net/npm/three@0.160.0/build/three.module.min.js'];
  let last;
  for(const src of tries){
    try{return await Promise.race([import(src),sleep(8000)])}catch(e){last=e;console.warn('Three load failed',src,e)}
  }
  throw last||new Error('Three.js unavailable');
}
(async()=>{
  try{
    const THREE=await loadThree();
    const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
    const rnd=(a,b)=>a+Math.random()*(b-a),clamp=(v,a,b)=>Math.max(a,Math.min(b,v));
    const isTouch=matchMedia('(hover:none),(pointer:coarse)').matches;
    const ui={stage:$('#stage'),start:$('#start'),over:$('#over'),hud:$('#hud'),touch:$('#touch'),preview:$('#preview'),plus:$('#plus'),portrait:$('#portrait'),hp:$('#hp'),hpFill:$('#hpFill'),wave:$('#wave'),kills:$('#kills'),score:$('#score'),ammo:$('#ammo'),reserve:$('#reserve'),weaponName:$('#weaponName'),cameraLabel:$('#cameraLabel'),danger:$('#danger'),waveBanner:$('#waveBanner'),toast:$('#toast')};

    let renderer;
    try{renderer=new THREE.WebGLRenderer({antialias:!isTouch,powerPreference:'high-performance'});}catch(e){throw new Error('WebGL renderer failed: '+e.message)}
    renderer.setPixelRatio(Math.min(devicePixelRatio||1,isTouch?1.15:1.6));renderer.setSize(innerWidth,innerHeight);renderer.outputColorSpace=THREE.SRGBColorSpace;renderer.toneMapping=THREE.ACESFilmicToneMapping;renderer.toneMappingExposure=.95;ui.stage.replaceChildren(renderer.domElement);
    const scene=new THREE.Scene();scene.background=new THREE.Color(0x050806);scene.fog=new THREE.FogExp2(0x07100b,isTouch?.028:.019);
    const camera=new THREE.PerspectiveCamera(isTouch?67:58,innerWidth/innerHeight,.1,220);const clock=new THREE.Clock();
    scene.add(new THREE.HemisphereLight(0xb8cbbd,0x10140f,1.15));const moon=new THREE.DirectionalLight(0xd3dfd6,1.25);moon.position.set(-18,35,-12);scene.add(moon);
    const world=new THREE.Group(),dynamic=new THREE.Group();scene.add(world,dynamic);

    function tex(kind){const c=document.createElement('canvas');c.width=c.height=192;const x=c.getContext('2d');const b=kind==='grass'?[31,51,30]:kind==='road'?[35,39,37]:[65,53,39];x.fillStyle=`rgb(${b.join(',')})`;x.fillRect(0,0,192,192);for(let i=0;i<2600;i++){const n=rnd(-20,20);x.fillStyle=`rgba(${clamp(b[0]+n,0,255)},${clamp(b[1]+n,0,255)},${clamp(b[2]+n,0,255)},${rnd(.05,.17)})`;x.fillRect(rnd(0,192),rnd(0,192),rnd(.5,2),rnd(.5,2))}const t=new THREE.CanvasTexture(c);t.wrapS=t.wrapT=THREE.RepeatWrapping;t.repeat.set(kind==='grass'?22:8,kind==='grass'?22:4);t.colorSpace=THREE.SRGBColorSpace;return t}
    const ground=new THREE.Mesh(new THREE.PlaneGeometry(180,180),new THREE.MeshStandardMaterial({map:tex('grass'),color:0x9caa91,roughness:1}));ground.rotation.x=-Math.PI/2;world.add(ground);
    const road=new THREE.Mesh(new THREE.PlaneGeometry(140,15),new THREE.MeshStandardMaterial({map:tex('road'),color:0x858b87,roughness:.76,metalness:.05}));road.rotation.x=-Math.PI/2;road.rotation.z=-.16;road.position.y=.02;world.add(road);
    for(let i=0;i<16;i++){const p=new THREE.Mesh(new THREE.CircleGeometry(rnd(1.1,3.5),18),new THREE.MeshPhysicalMaterial({color:0x647470,roughness:.18,metalness:.18,transparent:true,opacity:.32}));p.rotation.x=-Math.PI/2;p.position.set(rnd(-70,70),.03,rnd(-70,70));p.scale.y=rnd(.35,.8);world.add(p)}
    for(let i=0;i<18;i++){const p=new THREE.Mesh(new THREE.CircleGeometry(rnd(2,7),18),new THREE.MeshStandardMaterial({map:tex('dirt'),color:0x806c54,roughness:1,transparent:true,opacity:.55}));p.rotation.x=-Math.PI/2;p.position.set(rnd(-70,70),.025,rnd(-70,70));p.scale.y=rnd(.45,1);world.add(p)}

    const grassN=isTouch?420:1200,geo=new THREE.ConeGeometry(.05,.65,3);geo.translate(0,.325,0);const blades=new THREE.InstancedMesh(geo,new THREE.MeshStandardMaterial({color:0x476d3c,roughness:1}),grassN);const mat=new THREE.Matrix4(),q=new THREE.Quaternion(),sc=new THREE.Vector3(),pv=new THREE.Vector3();
    for(let i=0;i<grassN;i++){let x,z;do{x=rnd(-85,85);z=rnd(-85,85)}while(Math.abs(z+.16*x)<8);q.setFromAxisAngle(new THREE.Vector3(0,1,0),rnd(0,Math.PI*2));sc.set(rnd(.7,1.5),rnd(.6,1.55),rnd(.7,1.5));mat.compose(pv.set(x,.02,z),q,sc);blades.setMatrixAt(i,mat)}world.add(blades);

    function tree(x,z,s=1){const g=new THREE.Group();const tr=new THREE.Mesh(new THREE.CylinderGeometry(.2,.34,3.5,7),new THREE.MeshStandardMaterial({color:0x443526,roughness:1}));tr.position.y=1.75;g.add(tr);const cm=new THREE.MeshStandardMaterial({color:0x244427,roughness:1});for(const [ox,oy,oz,k] of [[0,3.9,0,1.35],[-.65,3.55,.15,1],[.6,3.5,-.15,.95]]){const c=new THREE.Mesh(new THREE.IcosahedronGeometry(1.2,1),cm);c.position.set(ox,oy,oz);c.scale.setScalar(k);g.add(c)}g.position.set(x,0,z);g.scale.setScalar(s);world.add(g)}
    for(let i=0;i<22;i++){let x=rnd(-80,80),z=rnd(-80,80);if(Math.abs(z+.16*x)<10){i--;continue}tree(x,z,rnd(.7,1.2))}
    for(let i=-2;i<=2;i++){const x=i*25,z=-.16*x+8;const pole=new THREE.Mesh(new THREE.CylinderGeometry(.07,.1,5,8),new THREE.MeshStandardMaterial({color:0x303733,metalness:.5}));pole.position.set(x,2.5,z);world.add(pole);const l=new THREE.PointLight(0xc6dc93,7,13,2);l.position.set(x,4.8,z);scene.add(l)}

    const rainN=isTouch?180:420,rpos=new Float32Array(rainN*3);for(let i=0;i<rainN;i++){rpos[i*3]=rnd(-55,55);rpos[i*3+1]=rnd(2,30);rpos[i*3+2]=rnd(-55,55)}const rg=new THREE.BufferGeometry();rg.setAttribute('position',new THREE.BufferAttribute(rpos,3));const rain=new THREE.Points(rg,new THREE.PointsMaterial({color:0xabc4bb,size:.05,transparent:true,opacity:.35,depthWrite:false}));scene.add(rain);

    let player=null,running=false,gameOver=false,cameraMode=boot.selectedCamera||'top',enemies=[],shots=[],wave=1,kills=0,score=0,spawnLeft=0,spawnTimer=0,nextWave=1.2,fireHeld=false,moveTouch={x:0,y:0};
    const keys=new Set(),pointer=new THREE.Vector2(),ray=new THREE.Raycaster(),plane=new THREE.Plane(new THREE.Vector3(0,1,0),0),hit=new THREE.Vector3();
    const W={pistol:{name:'PISTOL',mag:12,reserve:84,damage:38,rate:.21,speed:52,pellets:1,spread:.01},shotgun:{name:'SHOTGUN',mag:6,reserve:32,damage:24,rate:.72,speed:45,pellets:7,spread:.13},bow:{name:'BOW',mag:1,reserve:34,damage:110,rate:.76,speed:34,pellets:1,spread:.005}};
    let faceTex=null;
    function humanoid(z=false){const g=new THREE.Group();const bm=new THREE.MeshStandardMaterial({color:z?0x475349:0x34453b,roughness:.9}),body=new THREE.Mesh(new THREE.BoxGeometry(.9,1.35,.48),bm);body.position.y=1.55;g.add(body);const head=new THREE.Mesh(new THREE.SphereGeometry(.38,12,8),new THREE.MeshStandardMaterial({color:z?0x758272:0xb1a48d,roughness:.8}));head.position.y=2.65;g.add(head);for(const side of [-1,1]){const lm=new THREE.MeshStandardMaterial({color:z?0x3c473e:0x18211d,roughness:1}),arm=new THREE.Mesh(new THREE.BoxGeometry(.22,1.05,.24),lm),leg=new THREE.Mesh(new THREE.BoxGeometry(.27,1.15,.32),lm);arm.position.set(side*.58,1.5,0);leg.position.set(side*.24,.55,0);g.add(arm,leg)}if(!z){const face=new THREE.Mesh(new THREE.PlaneGeometry(.54,.62),new THREE.MeshBasicMaterial({color:0xffffff,map:faceTex||null}));face.position.set(0,2.67,.382);g.add(face);g.userData.face=face;const gun=new THREE.Mesh(new THREE.BoxGeometry(.13,.13,1),new THREE.MeshStandardMaterial({color:0x222a26,metalness:.6}));gun.position.set(.42,1.75,.72);g.add(gun)}return g}
    function neutral(){const c=document.createElement('canvas');c.width=c.height=180;const x=c.getContext('2d');x.fillStyle='#59645b';x.fillRect(0,0,180,180);x.fillStyle='#adb6aa';x.beginPath();x.arc(90,80,38,0,Math.PI*2);x.fill();return c.toDataURL('image/jpeg',.82)}
    function applyFace(src){ui.preview.src=src;ui.preview.style.display='block';ui.plus.style.display='none';ui.portrait.src=src;new THREE.TextureLoader().load(src,t=>{t.colorSpace=THREE.SRGBColorSpace;faceTex=t;if(player?.mesh?.userData.face){player.mesh.userData.face.material.map=t;player.mesh.userData.face.material.needsUpdate=true}})}
    let saved=null;try{saved=localStorage.getItem('facefall-face')}catch{}applyFace(saved||neutral());
    $('#face').addEventListener('change',e=>{const f=e.target.files?.[0];if(!f)return;const r=new FileReader();r.onload=()=>{const im=new Image();im.onload=()=>{const c=document.createElement('canvas');c.width=c.height=320;const x=c.getContext('2d'),s=Math.max(320/im.width,320/im.height),w=im.width*s,h=im.height*s;x.drawImage(im,(320-w)/2,(320-h)/2,w,h);const d=c.toDataURL('image/jpeg',.84);try{localStorage.setItem('facefall-face',d)}catch{}applyFace(d)};im.src=r.result};r.readAsDataURL(f)});

    function toast(t){ui.toast.textContent=t;ui.toast.classList.remove('hidden');clearTimeout(toast._t);toast._t=setTimeout(()=>ui.toast.classList.add('hidden'),1000)}
    function reset(){dynamic.clear();enemies=[];shots=[];wave=1;kills=0;score=0;spawnLeft=0;nextWave=1.1;gameOver=false;const mesh=humanoid(false);dynamic.add(mesh);player={mesh,x:0,z:0,yaw:0,hp:100,speed:8,weapon:'pistol',cool:0,ammo:{pistol:{mag:12,reserve:84},shotgun:{mag:6,reserve:32},bow:{mag:1,reserve:34}}};hud()}
    function hud(){if(!player)return;ui.hp.textContent=Math.ceil(player.hp);ui.hpFill.style.width=clamp(player.hp,0,100)+'%';ui.wave.textContent=wave;ui.kills.textContent=kills;ui.score.textContent=String(score).padStart(6,'0');const a=player.ammo[player.weapon],w=W[player.weapon];ui.weaponName.textContent=w.name;ui.ammo.textContent=a.mag;ui.reserve.textContent=' / '+a.reserve;ui.cameraLabel.textContent=cameraMode==='third'?'THIRD PERSON':'TOP-DOWN'}
    function setCamera(mode,announce=true){cameraMode=mode==='third'?'third':'top';boot.selectedCamera=cameraMode;$$('[data-camera]').forEach(b=>b.classList.toggle('active',b.dataset.camera===cameraMode));hud();if(announce&&running)toast(cameraMode==='third'?'THIRD PERSON':'TOP-DOWN')}
    function start(){reset();setCamera(boot.selectedCamera,false);running=true;ui.start.classList.add('hidden');ui.over.classList.add('hidden');ui.hud.classList.remove('hidden');if(isTouch)ui.touch.classList.remove('hidden');clock.start();toast('SURVIVE THE NIGHT')}
    function end(){if(gameOver)return;gameOver=true;running=false;fireHeld=false;ui.hud.classList.add('hidden');ui.touch.classList.add('hidden');$('#finalScore').textContent=score;$('#finalKills').textContent=kills;$('#finalWave').textContent=wave;ui.over.classList.remove('hidden')}
    function spawn(){const a=rnd(0,Math.PI*2),d=rnd(30,42),mesh=humanoid(true),x=player.x+Math.sin(a)*d,z=player.z+Math.cos(a)*d;mesh.position.set(x,0,z);dynamic.add(mesh);enemies.push({mesh,x,z,hp:70+wave*7,speed:2.8+wave*.06,damage:14,attack:0})}
    function beginWave(){spawnLeft=5+wave*3;spawnTimer=.1;ui.waveBanner.querySelector('b').textContent=wave;ui.waveBanner.classList.remove('hidden');setTimeout(()=>ui.waveBanner.classList.add('hidden'),1000)}
    function weapon(id){if(!player||!W[id])return;player.weapon=id;$$('.slots button').forEach(b=>b.classList.toggle('active',b.dataset.w===id));hud()}
    function shoot(){if(!running||gameOver||player.cool>0)return;const w=W[player.weapon],a=player.ammo[player.weapon];if(a.mag<=0){toast('НЕТ ПАТРОНОВ');return}if(isTouch&&enemies.length){let e=enemies[0],bd=999;for(const q of enemies){const d=Math.hypot(q.x-player.x,q.z-player.z);if(d<bd){bd=d;e=q}}player.yaw=Math.atan2(e.x-player.x,e.z-player.z)}a.mag--;player.cool=w.rate;for(let i=0;i<w.pellets;i++){const ang=player.yaw+rnd(-w.spread,w.spread),dir=new THREE.Vector3(Math.sin(ang),0,Math.cos(ang)),mesh=new THREE.Mesh(new THREE.SphereGeometry(.05,5,4),new THREE.MeshBasicMaterial({color:0xffd58a}));mesh.position.set(player.x,1.7,player.z);dynamic.add(mesh);shots.push({mesh,dir,speed:w.speed,damage:w.damage,life:1.2})}hud()}
    function update(dt){const rp=rain.geometry.attributes.position.array;for(let i=0;i<rp.length;i+=3){rp[i+1]-=dt*18;if(rp[i+1]<0)rp[i+1]=rnd(18,30)}rain.geometry.attributes.position.needsUpdate=true;if(!running||!player)return;player.cool=Math.max(0,player.cool-dt);let mx=(keys.has('d')?1:0)-(keys.has('a')?1:0),mz=(keys.has('s')?1:0)-(keys.has('w')?1:0);if(isTouch){mx+=moveTouch.x;mz+=moveTouch.y}const ml=Math.hypot(mx,mz);if(ml>.05){mx/=ml;mz/=ml;player.x=clamp(player.x+mx*player.speed*dt,-80,80);player.z=clamp(player.z+mz*player.speed*dt,-80,80)}if(cameraMode==='top'&&!isTouch){ray.setFromCamera(pointer,camera);if(ray.ray.intersectPlane(plane,hit))player.yaw=Math.atan2(hit.x-player.x,hit.z-player.z)}player.mesh.position.set(player.x,0,player.z);player.mesh.rotation.y=player.yaw;if(fireHeld)shoot();for(let i=enemies.length-1;i>=0;i--){const e=enemies[i],dx=player.x-e.x,dz=player.z-e.z,d=Math.hypot(dx,dz)||1;e.attack-=dt;if(d>1.3){e.x+=dx/d*e.speed*dt;e.z+=dz/d*e.speed*dt}else if(e.attack<=0){e.attack=.8;player.hp-=e.damage;if(player.hp<=0){end();return}}e.mesh.position.set(e.x,0,e.z);e.mesh.rotation.y=Math.atan2(dx,dz)}for(let i=shots.length-1;i>=0;i--){const s=shots[i];s.life-=dt;s.mesh.position.addScaledVector(s.dir,s.speed*dt);let target=null;for(const e of enemies){const dx=s.mesh.position.x-e.x,dz=s.mesh.position.z-e.z;if(dx*dx+dz*dz<1){target=e;break}}if(target){target.hp-=s.damage;dynamic.remove(s.mesh);shots.splice(i,1);if(target.hp<=0){dynamic.remove(target.mesh);enemies.splice(enemies.indexOf(target),1);kills++;score+=100}continue}if(s.life<=0){dynamic.remove(s.mesh);shots.splice(i,1)}}if(nextWave>0){nextWave-=dt;if(nextWave<=0)beginWave()}if(spawnLeft>0){spawnTimer-=dt;if(spawnTimer<=0){spawn();spawnLeft--;spawnTimer=.55}}if(spawnLeft===0&&enemies.length===0&&nextWave<=0){wave++;nextWave=2}const f=new THREE.Vector3(Math.sin(player.yaw),0,Math.cos(player.yaw));const desired=cameraMode==='third'?new THREE.Vector3(player.x-f.x*7,4.4,player.z-f.z*7):new THREE.Vector3(player.x,30,player.z+17),look=cameraMode==='third'?new THREE.Vector3(player.x+f.x*5,1.7,player.z+f.z*5):new THREE.Vector3(player.x,0,player.z-2);camera.position.lerp(desired,1-Math.pow(.001,dt));camera.lookAt(look);hud()}
    function loop(){const dt=Math.min(.035,clock.getDelta()||.016);update(dt);renderer.render(scene,camera);requestAnimationFrame(loop)}
    addEventListener('resize',()=>{camera.aspect=innerWidth/innerHeight;camera.updateProjectionMatrix();renderer.setSize(innerWidth,innerHeight)});addEventListener('keydown',e=>{keys.add(e.key.toLowerCase());if(e.key==='1')weapon('pistol');if(e.key==='2')weapon('shotgun');if(e.key==='3')weapon('bow');if(e.key.toLowerCase()==='c')setCamera(cameraMode==='top'?'third':'top')});addEventListener('keyup',e=>keys.delete(e.key.toLowerCase()));addEventListener('mousemove',e=>{pointer.x=e.clientX/innerWidth*2-1;pointer.y=-(e.clientY/innerHeight)*2+1});renderer.domElement.addEventListener('mousedown',()=>{fireHeld=true;shoot()});addEventListener('mouseup',()=>fireHeld=false);
    $('#cameraToggle').addEventListener('click',()=>setCamera(cameraMode==='top'?'third':'top'));$$('.slots button').forEach(b=>b.addEventListener('click',()=>weapon(b.dataset.w)));$('#again').addEventListener('click',start);
    const joy=$('#joy'),stick=$('#stick');if(joy&&stick){let jid=null;const jm=t=>{const r=joy.getBoundingClientRect(),cx=r.left+r.width/2,cy=r.top+r.height/2,max=r.width*.3;let dx=t.clientX-cx,dy=t.clientY-cy,m=Math.hypot(dx,dy);if(m>max){dx=dx/m*max;dy=dy/m*max}moveTouch={x:dx/max,y:dy/max};stick.style.transform=`translate(${dx}px,${dy}px)`};joy.addEventListener('touchstart',e=>{jid=e.changedTouches[0].identifier;jm(e.changedTouches[0]);e.preventDefault()},{passive:false});joy.addEventListener('touchmove',e=>{for(const t of e.changedTouches)if(t.identifier===jid)jm(t);e.preventDefault()},{passive:false});joy.addEventListener('touchend',e=>{jid=null;moveTouch={x:0,y:0};stick.style.transform='translate(0,0)';e.preventDefault()},{passive:false})}
    $('#fire').addEventListener('touchstart',e=>{fireHeld=true;shoot();e.preventDefault()},{passive:false});$('#fire').addEventListener('touchend',e=>{fireHeld=false;e.preventDefault()},{passive:false});$('#swap').addEventListener('click',()=>{const ids=['pistol','shotgun','bow'],i=ids.indexOf(player?.weapon||'pistol');weapon(ids[(i+1)%3])});$('#reload').addEventListener('click',()=>toast('AUTO RELOAD NEXT'));
    reset();camera.position.set(0,30,17);camera.lookAt(0,0,-2);loop();
    window.FacefallEngine={start,setCamera};window.dispatchEvent(new CustomEvent('facefall-engine-ready'));if(boot.pendingStart)start();
  }catch(err){console.error(err);window.dispatchEvent(new CustomEvent('facefall-engine-error',{detail:'Ошибка 3D: '+(err?.message||String(err))}))}
})();
